# Generated by Django 4.1.13 on 2024-06-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVenda', models.CharField(max_length=8)),
                ('codigoVenda', models.CharField(max_length=5)),
                ('codigoCliente', models.CharField(max_length=5)),
                ('codigoFornecedor', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='rua',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='cep',
            field=models.CharField(default='', max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='endereço',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
