# Generated by Django 5.0.6 on 2024-06-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendamodel_remove_productmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'ProductModel', 'verbose_name_plural': 'ProductsModel'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'UserModel', 'verbose_name_plural': 'UsersModels'},
        ),
        migrations.AlterModelOptions(
            name='vendamodel',
            options={'verbose_name': 'VendaModel', 'verbose_name_plural': 'VendaModel'},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='Users',
        ),
    ]
