# Generated by Django 4.1.13 on 2024-06-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productmodel_options_alter_usermodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='telefone',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
